apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hipstergram-users
  template:
    metadata:
      labels:
        app: hipstergram-users
    spec:
      containers:
        - image: klemenstanic/users-api:latest
          name: users-api
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: db-connection-url-users-api
            - name: LOGS_URI 
              valueFrom:
                secretKeyRef:
                  name: log-connection 
                  key: log-connection-url 
            - name: LOGS_PORT
              valueFrom:
                secretKeyRef:
                  name: log-connection
                  key: log-connection-port

          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: users-api
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: hipstergram-users
